services:
  - type: web
    name: skillbridge-backend
    env: node
    buildCommand: npm install --prefix server
    startCommand: node server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 4000

  - type: web
    name: skillbridge-frontend
    env: static
    buildCommand: npm install --prefix client && npm run build --prefix client
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        sync: false

